services:
  db:
    image: postgres
    restart: always
    container_name: postgresql
    networks:
      - recargapay
    environment:
      - POSTGRES_DB=wallet
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    volumes:
      - ./database/db.sql:/docker-entrypoint-initdb.d/database.sql
    ports:
      - 5432:5432

  api:
    image: eclipse-temurin:21-jdk
    container_name: wallet-api
    depends_on:
      - db
    networks:
      - recargapay
    environment:
      - DATASOURCES_DEFAULT_URL=jdbc:postgresql://db:5432/wallet
      - DATASOURCES_DEFAULT_USERNAME=admin
      - DATASOURCES_DEFAULT_PASSWORD=admin
    volumes:
      - ./target/wallet-service-1.0.jar:/app/app.jar
      - ./wait-for-db.sh:/app/wait-for-db.sh
    working_dir: /app
    command: [ "java", "-jar", "app.jar" ]
    ports:
      - 8080:8080

networks:
  recargapay:
    driver: bridge